Update schema_input.json: require filtered or filtered
nf-core/scdownstream pull request #63
Opened 2024-07-10 20:04 UTC by smoe

The sample sheet format has changed. This extra check shall help directing the users, and if it is only to have them reread the documentation.

This PR was triggered by me running into an unexpected and apparently unrelated error message - which may warrant another PR, need to chase that up, still.

2024-07-11 09:54 UTC, smoe commented
This gets an `ERROR ~ Unexpected error [NullPointerException]` early on. Can anybody reproduce this locally?

2024-07-15 19:33 UTC, nictru requested changes

2024-07-15 19:33 UTC, nictru commented on assets/schema_input.json
> +        "oneOf": [
```suggestion
        "anyOf": [
```

Based on the documentation [here](https://json-schema.org/understanding-json-schema/reference/combining), `oneOf` would be an XOR, which is not what we want here

2024-07-15 19:38 UTC, nictru approved these changes

2024-07-15 19:40 UTC, nictru commented
Sorry that it took me so long to respond, was not aware of this open PR - but thanks for the contribution!

2024-07-15 19:40 UTC, merged